#!/usr/bin/env bash

echo "Moving jekyllMarkdownTaggerPlugin.rb to _plugins"
mv rosey-connector/ssgs/jekyllMarkdownTaggerPlugin.rb site/_plugins/jekyllMarkdownTaggerPlugin.rb
echo "Moved jekyllMarkdownTaggerPlugin.rb to _plugins!"
echo "Moving jekyllImageUnwrapPlugin.rb to _plugins"
mv rosey-connector/ssgs/jekyllImageUnwrapPlugin.rb site/_plugins/jekyllImageUnwrapPlugin.rb
echo "Moved jekyllImageUnwrapPlugin.rb to _plugins!"